### ISSUE TITLE
Greek island, Crete gives undefined or wrong country.

### ISSUE THREAD

**Issue by ghost** [ChengCPU/visa-map#9]
The Greek island, Crete gives a undefined name when hovering over it. Hovering over any other country displays the name of the country on the island while it should be Greek.

Steps to reproduce undefined:
- Hover over the island of Crete without hovering over any other country and getting a tooltip. 

![afbeelding](https://github.com/ChengCPU/visa-map/assets/167819382/fb0165cb-1c87-4e30-a5e4-4f4a3bcbf7c3)

When you hover over the any other country and get the tooltip the island Crete will give the last place you hovered over. See image where I hovered over Libya and then Crete right after.

![afbeelding](https://github.com/ChengCPU/visa-map/assets/167819382/29aa5efb-f656-4d20-8ff1-faad50aca557)

Here one with Vatican City:

![afbeelding](https://github.com/ChengCPU/visa-map/assets/167819382/8ef27897-d897-4e8a-b199-ee38f7610c65)

Crete is part of Greece and should have the tooltip Greece.

**Comment by ChengCPU** [comment]
Fixed, there was just a little line of code missing on the SVG <g> component that makes up the two parts of Greece. It was missing this code that is passed into the information box on hover:
```
onMouseOver={() => setCountrySelect('greece')}
```
